/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      boxShadow: {
        card: 'var(--palette-card-shadow)',
      },
      colors: {
        tertiary: 'var(--palette-tertiary)',
        'tertiary-fixed': 'var(--palette-tertiary-fixed)',
        'tertiary-fixed-dim': 'var(--palette-tertiary-fixed-dim)',
        'surface-container-highest': 'var(--palette-surface-container-highest)',
        'on-tertiary-fixed': 'var(--palette-on-tertiary-fixed)',
        'primary-fixed-dim': 'var(--palette-primary-fixed-dim)',
        'on-error-container': 'var(--palette-on-error-container)',
        'surface-container-low': 'var(--palette-surface-container-low)',
        'on-surface-variant': 'var(--palette-on-surface-variant)',
        'on-tertiary-container': 'var(--palette-on-tertiary-container)',
        'surface-container-high': 'var(--palette-surface-container-high)',
        'secondary-fixed': 'var(--palette-secondary-fixed)',
        outline: 'var(--palette-outline)',
        'on-secondary': 'var(--palette-on-secondary)',
        'on-primary-fixed-variant': 'var(--palette-on-primary-fixed-variant)',
        'primary-fixed': 'var(--palette-primary-fixed)',
        'on-background': 'var(--palette-on-background)',
        'inverse-on-surface': 'var(--palette-inverse-on-surface)',
        'surface-variant': 'var(--palette-surface-variant)',
        'surface-tint': 'var(--palette-surface-tint)',
        'surface-container-lowest': 'var(--palette-surface-container-lowest)',
        'inverse-surface': 'var(--palette-inverse-surface)',
        'surface-dim': 'var(--palette-surface-dim)',
        'on-secondary-fixed-variant': 'var(--palette-on-secondary-fixed-variant)',
        'tertiary-container': 'var(--palette-tertiary-container)',
        background: 'var(--palette-background)',
        'surface-bright': 'var(--palette-surface-bright)',
        'outline-variant': 'var(--palette-outline-variant)',
        'on-tertiary': 'var(--palette-on-tertiary)',
        'on-error': 'var(--palette-on-error)',
        surface: 'var(--palette-surface)',
        'on-secondary-container': 'var(--palette-on-secondary-container)',
        'inverse-primary': 'var(--palette-inverse-primary)',
        'surface-container': 'var(--palette-surface-container)',
        secondary: 'var(--palette-secondary)',
        'on-primary-fixed': 'var(--palette-on-primary-fixed)',
        'on-primary': 'var(--palette-on-primary)',
        'secondary-container': 'var(--palette-secondary-container)',
        primary: 'rgb(var(--palette-primary-rgb) / <alpha-value>)',
        'primary-strong': 'rgb(var(--palette-primary-strong-rgb) / <alpha-value>)',
        'on-surface': 'var(--palette-on-surface)',
        error: 'rgb(var(--palette-error-rgb) / <alpha-value>)',
        'primary-container': 'var(--palette-primary-container)',
        'on-tertiary-fixed-variant': 'var(--palette-on-tertiary-fixed-variant)',
        'on-primary-container': 'var(--palette-on-primary-container)',
        'secondary-fixed-dim': 'var(--palette-secondary-fixed-dim)',
        'error-container': 'var(--palette-error-container)',
        'on-secondary-fixed': 'var(--palette-on-secondary-fixed)',
        scrim: 'rgb(var(--palette-scrim-rgb) / <alpha-value>)',
        'on-media': 'rgb(var(--palette-on-media-rgb) / <alpha-value>)',
        'accent-highlight': 'rgb(var(--palette-accent-highlight-rgb) / <alpha-value>)',
        success: 'rgb(var(--palette-success-rgb) / <alpha-value>)',
        footer: 'rgb(var(--palette-footer-bg-rgb) / <alpha-value>)',
        'on-footer': 'rgb(var(--palette-footer-fg-rgb) / <alpha-value>)',
        'admin-sidebar': 'var(--palette-admin-sidebar)',
        'rating-star': 'var(--palette-rating-star)',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        'stack-sm': '16px',
        'stack-md': '32px',
        unit: '8px',
        'margin-edge': '40px',
        'container-max': '1280px',
        'stack-lg': '64px',
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'sans-serif'],
        'body-md': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'label-caps': ['Plus Jakarta Sans', 'sans-serif'],
        'display-xl': ['Plus Jakarta Sans', 'sans-serif'],
        'body-lg': ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
        'display-xl': ['64px', { lineHeight: '72px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        'label-bold': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
